# Generated by Django 4.2.9 on 2024-01-21 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/ProductPic/')),
                ('quantity', models.IntegerField(default=0)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('totalprice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_indivisual', models.BooleanField(default=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTotalSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='DateTotalSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='DateProductTotalSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client_TotalSales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('ts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.totalsales')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Sales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Client_ProductTotalSales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('dts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producttotalsales')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Product_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client_DateTotalSales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('dts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.datetotalsales')),
            ],
        ),
        migrations.CreateModel(
            name='Client_DateProductTotalSales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('dts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dateproducttotalsales')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/CustomerProfilePic/')),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
